/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppExamsRouteImport } from './routes/app/exams'
import { Route as AppQuestionsRouteImport } from './routes/app/questions'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppExamBuilderExamIdRouteImport } from './routes/app/exam-builder.$examId'
import { Route as AppExamReadExamIdRouteImport } from './routes/app/exam-read.$examId'
import { Route as AppExamExamIdRouteImport } from './routes/app/exam.$examId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionsRoute = AppQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExamBuilderExamIdRoute = AppExamBuilderExamIdRouteImport.update({
  id: '/exam-builder/$examId',
  path: '/exam-builder/$examId',
  getParentRoute: () => AppRoute,
} as any)
const AppExamReadExamIdRoute = AppExamReadExamIdRouteImport.update({
  id: '/exam-read/$examId',
  path: '/exam-read/$examId',
  getParentRoute: () => AppRoute,
} as any)
const AppExamExamIdRoute = AppExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/exams': typeof AppExamsRoute
  '/app/questions': typeof AppQuestionsRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/exam-builder/$examId': typeof AppExamBuilderExamIdRoute
  '/app/exam-read/$examId': typeof AppExamReadExamIdRoute
  '/app/exam/$examId': typeof AppExamExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/exams': typeof AppExamsRoute
  '/app/questions': typeof AppQuestionsRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/exam-builder/$examId': typeof AppExamBuilderExamIdRoute
  '/app/exam-read/$examId': typeof AppExamReadExamIdRoute
  '/app/exam/$examId': typeof AppExamExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/exams': typeof AppExamsRoute
  '/app/questions': typeof AppQuestionsRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/exam-builder/$examId': typeof AppExamBuilderExamIdRoute
  '/app/exam-read/$examId': typeof AppExamReadExamIdRoute
  '/app/exam/$examId': typeof AppExamExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/exams'
    | '/app/questions'
    | '/app/'
    | '/api/auth/$'
    | '/app/exam-builder/$examId'
    | '/app/exam-read/$examId'
    | '/app/exam/$examId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/exams'
    | '/app/questions'
    | '/app'
    | '/api/auth/$'
    | '/app/exam-builder/$examId'
    | '/app/exam-read/$examId'
    | '/app/exam/$examId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/exams'
    | '/app/questions'
    | '/app/'
    | '/api/auth/$'
    | '/app/exam-builder/$examId'
    | '/app/exam-read/$examId'
    | '/app/exam/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exams': {
      id: '/app/exams'
      path: '/exams'
      fullPath: '/app/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/questions': {
      id: '/app/questions'
      path: '/questions'
      fullPath: '/app/questions'
      preLoaderRoute: typeof AppQuestionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/exam-builder/$examId': {
      id: '/app/exam-builder/$examId'
      path: '/exam-builder/$examId'
      fullPath: '/app/exam-builder/$examId'
      preLoaderRoute: typeof AppExamBuilderExamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exam-read/$examId': {
      id: '/app/exam-read/$examId'
      path: '/exam-read/$examId'
      fullPath: '/app/exam-read/$examId'
      preLoaderRoute: typeof AppExamReadExamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exam/$examId': {
      id: '/app/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/app/exam/$examId'
      preLoaderRoute: typeof AppExamExamIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppExamsRoute: typeof AppExamsRoute
  AppQuestionsRoute: typeof AppQuestionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExamBuilderExamIdRoute: typeof AppExamBuilderExamIdRoute
  AppExamReadExamIdRoute: typeof AppExamReadExamIdRoute
  AppExamExamIdRoute: typeof AppExamExamIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExamsRoute: AppExamsRoute,
  AppQuestionsRoute: AppQuestionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppExamBuilderExamIdRoute: AppExamBuilderExamIdRoute,
  AppExamReadExamIdRoute: AppExamReadExamIdRoute,
  AppExamExamIdRoute: AppExamExamIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
